apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks
    buildpacks:
      builder: "paketobuildpacks/builder:base"
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
